# docker compose build - используем эту команду, если меняли что-то в Dockerfile
# docker compose up - если изменили только docker-compose

version: "3.8"
services:
  web:
    build: .
    container_name: rss_aggregator
    env_file:
      - .env-non-dev
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    container_name: rss_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env-non-dev
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: rss_redis
    env_file:
      - .env-non-dev
    volumes:
      - redis_data:/data

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    container_name: rss_postgres_exporter
    env_file:
      - .env-non-dev
    environment:
      - DATA_SOURCE_NAME=postgresql://${DB_USER}:${DB_PASS}@db:${DB_PORT}/${DB_NAME}?sslmode=disable
    depends_on:
      - db

  redis_exporter:
    image: oliver006/redis_exporter:latest
    container_name: rss_redis_exporter
    env_file:
      - .env-non-dev
    environment:
      - REDIS_ADDR=redis://${REDIS_HOST}:${REDIS_PORT}
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:latest
    container_name: rss_prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: rss_grafana
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - .env-non-dev
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - "3000:3000"

  celery_worker:
    build: .
    container_name: rss_celery_worker
    env_file:
      - .env-non-dev
    command: celery -A app.tasks.celery_app worker --loglevel=info
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    container_name: rss_celery_beat
    env_file:
      - .env-non-dev
    command: >
      sh -c "
        rm -f celerybeat-schedule* &&
        celery -A app.tasks.celery_app beat --loglevel=info
      "
    depends_on:
      - db
      - redis

  celery_flower:
    build: .
    container_name: rss_celery_flower
    env_file:
      - .env-non-dev
    command: celery -A app.tasks.celery_app flower --port=5555
    depends_on:
      - db
      - redis
      - celery_worker
    ports:
      - "5555:5555"

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data: