"""empty message

Revision ID: ad60bb7830d3
Revises: 40d62638271e
Create Date: 2025-10-14 23:06:15.361464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad60bb7830d3'
down_revision: Union[str, Sequence[str], None] = '40d62638271e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('articles_link_key'), 'articles', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('articles_link_key'), 'articles', ['link'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
