"""empty message

Revision ID: e5cc63b1efb9
Revises: 3f4287c70358
Create Date: 2025-10-04 14:13:45.482726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5cc63b1efb9'
down_revision: Union[str, Sequence[str], None] = '3f4287c70358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('normalized_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeds', 'normalized_url')
    # ### end Alembic commands ###
